app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Marca'

outflows/models.py
from django.db import models
from products.models import Product


class Outflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    quantity = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.product)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Saída'

products/models.py
from django.db import models
from brands.models import Brand
from categories.models import Category


class Product(models.Model):
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products')
    description = models.TextField(null=True, blank=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Produto'

inflows/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from . import models
from . import forms
from app import metrics
from . import serializers
from categories.models import Category
from brands.models import Brand


class InflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 10
    permission_required = 'inflows.view_inflow'

    def get_queryset(self):
        queryset = super().get_queryset()
        product = self.request.GET.get('product')

        if product:
            queryset = queryset.filter(product__title__icontains=product)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        context['product_metrics'] = metrics.get_product_metrics()
        return context


class InflowCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Inflow
    template_name = 'inflow_create.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')
    permission_required = 'inflows.add_inflow'


class InflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'
    permission_required = 'inflows.view_inflow'


class InflowListCreateAPIView(generics.ListCreateAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer


class InflowRetrieveAPIView(generics.RetrieveAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer

app/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <span class="text-muted">© 2024 SGE</span>
  </div>
</footer>

app/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="">Sistema de Gestão de Estoque (SGE)</a>
  </div>
</nav>

app/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Primeira
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Anterior
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Próxima
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Última
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

app/templates/components/_product_metrics.html
<div class="card mt-4">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="card bg-primary">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Quantidade de Produtos</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              {{ product_metrics.total_quantity }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-danger">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Custo de Estoque</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              R$ {{ product_metrics.total_cost_price }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-success">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Valor do Estoque</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              R$ {{ product_metrics.total_selling_price }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-warning">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Lucro de Estoque</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              R$ {{ product_metrics.total_profit }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/components/_sales_metrics.html
<div class="card mt-4">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="card bg-primary">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Quantidade de Vendas</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              {{ sales_metrics.total_sales }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-danger">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Produtos Vendidos</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              {{ sales_metrics.total_products_sold }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-success">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Valor das Vendas</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              R$ {{ sales_metrics.total_sales_value }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-warning">
          <div class="card-body d-flex flex-column justify-content-center align-items-center" style="height: 100px;">
            <h5 class="card-title text-center">Lucro das Vendas</h5>
            <p class="card-text text-white font-weight-bold display-6" style="white-space: nowrap; font-size: 1.5rem;">
              R$ {{ sales_metrics.total_sales_profit }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/components/_sidebar.html
<div class="row flex-nowrap">
  <div class="col-auto col-md-0 col-xl-0 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white">
      <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
        <i class="bi bi-list fs-4"></i>
      </button>
      <div class="collapse d-sm-block" id="menuCollapse">
        <ul class="nav flex-column align-items-start" id="menu">

          <li>
            <a href="{% url 'home' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-speedometer2 fs-4"></i>
              <span class="ms-1">Dashboard</span>
            </a>
          </li>

          {% if perms.suppliers.view_supplier %}
          <li>
            <a href="{% url 'supplier_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-truck fs-4"></i>
              <span class="ms-1">Fornecedores</span>
            </a>
          </li>
          {% endif %}

          {% if perms.brands.view_brand %}
          <li>
            <a href="{% url 'brand_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-shop fs-4"></i>
              <span class="ms-1">Marcas</span>
            </a>
          </li>
          {% endif %}

          {% if perms.categories.view_category %}
          <li>
            <a href="{% url 'category_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-tags fs-4"></i>
              <span class="ms-1">Categorias</span>
            </a>
          </li>
          {% endif %}

          {% if perms.products.view_product %}
          <li>
            <a href="{% url 'product_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-box-seam fs-4"></i>
              <span class="ms-1">Produtos</span>
            </a>
          </li>
          {% endif %}

          {% if perms.inflows.view_inflow %}
          <li>
            <a href="{% url 'inflow_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-arrow-down-left-square fs-4"></i>
              <span class="ms-1">Entradas</span>
            </a>
          </li>
          {% endif %}

          {% if perms.outflows.view_outflow %}
          <li>
            <a href="{% url 'outflow_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-arrow-up-right-square fs-4"></i>
              <span class="ms-1">Saídas</span>
            </a>
          </li>
          {% endif %}

          <li class="nav-item">
            {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post" id="logout-form" class="nav-link px-0 align-middle">
              {% csrf_token %}
              <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                <span class="ms-1 align-middle">Logout</span>
              </button>
            </form>
            {% endif %}
          </li>

        </ul>
      </div>
      <hr>
    </div>
  </div>