app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

suppliers/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('suppliers/list/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/create/', views.SupplierCreateView.as_view(), name='supplier_create'),
    path('suppliers/<int:pk>/detail/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    path('suppliers/<int:pk>/update', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('suppliers/<int:pk>/delete', views.SupplierDeleteView.as_view(), name='supplier_delete'),

    path('api/v1/suppliers/', views.SupplierListCreateAPIView.as_view(), name='supplier_list_create_api_view'),
    path('api/v1/suppliers/<int:pk>/', views.SupplierRetrieveUpdateDestroyAPIView.as_view(), name='supplier_detail_api_view'),
]

suppliers/models.py
from django.db import models


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Fornecedor'

suppliers/forms.py
from django import forms
from . import models


class SupplierForm(forms.ModelForm):

    class Meta:
        model = models.Supplier
        fields = ['name', 'description', ]
        widgets = {
            'name': forms.TextInput({'class': 'form-control'}),
            'description': forms.Textarea({'class': 'form-control', 'rows': 3}),
        }
        labels = {
            'name': 'Nome',
            'description': 'Descrição'
        }

suppliers/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from . import models, forms, serializers


class SupplierListView(LoginRequiredMixin, ListView):
    model = models.Supplier
    template_name = 'supplier_list.html'
    context_object_name = 'suppliers'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')

        if name:
            queryset = queryset.filter(name__icontains=name)

        return queryset


class SupplierCreateView(LoginRequiredMixin, CreateView):
    model = models.Supplier
    template_name = 'supplier_create.html'
    form_class = forms.SupplierForm
    success_url = reverse_lazy('supplier_list')


class SupplierDetailView(LoginRequiredMixin, DetailView):
    model = models.Supplier
    template_name = 'supplier_detail.html'


class SupplierUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Supplier
    template_name = 'supplier_update.html'
    form_class = forms.SupplierForm
    success_url = reverse_lazy('supplier_list')


class SupplierDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Supplier
    template_name = 'supplier_delete.html'
    success_url = reverse_lazy('supplier_list')


class SupplierListCreateAPIView(generics.ListCreateAPIView):
    queryset = models.Supplier.objects.all()
    serializer_class = serializers.SupplierSerializer


class SupplierRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Supplier.objects.all()
    serializer_class = serializers.SupplierSerializer

suppliers/templates/supplier_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-4">Cadastrar Fornecedor</h3>

    <div class="card">
      <div class="card-body">
        <form method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Salvar Fornecedor</button>
        </form>
      </div>
    </div>
    <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Fornecedores</a>
  </div>
{% endblock %}

suppliers/templates/supplier_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Deletar Fornecedor</h3>

  <div class="card">
    <div class="card-body">
      <p class="card-text">Tem certeza de que deseja excluir o Fornecedor: <strong>{{ object.name }}</strong>?</p>

      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Deletar</button>
      </form>

      <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Fornecedores</a>
    </div>
  </div>
</div>
{% endblock %}

suppliers/templates/supplier_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-4">Detalhes do Fornecedor</h3>

    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ object.name }}</h3>
        <p class="card-text">{{ object.description }}</p>
      </div>
    </div>

    <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Voltar para a Lista de Fornecedores</a>
  </div>
{% endblock %}

suppliers/templates/supplier_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Fornecedores
{% endblock %}

{% block content %}

<div class="row mb-3">
  <div class="col-md-6">
    <form method="get" action="{% url 'supplier_list' %}">
      <div class="input-group">
        <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-search"></i>
        </button>
      </div>
    </form>
  </div>

  <div class="col-md-6">
    {% if perms.suppliers.add_supplier %}
    <a href="{% url 'supplier_create' %}" class="btn btn-success float-end">
      <i class="bi bi-plus"></i> Novo Fornecedor
    </a>
    {% endif %}
  </div>

</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for supplier in suppliers %}
      <tr>
        <td>
          <a href="{% url 'supplier_detail' supplier.id %}" class="text-primary fw-semibold">
            {{ supplier.id }}
          </a>
        </td>
        <td>{{ supplier.name }}</td>
        <td>{{ supplier.description }}</td>
        <td>

          <a href="{% url 'supplier_detail' supplier.id %}" class="btn btn-info btn-sm">
            <i class="bi bi-eye"></i>
          </a>

          {% if perms.suppliers.change_supplier %}
          <a href="{% url 'supplier_update' supplier.id %}" class="btn btn-warning btn-sm">
            <i class="bi bi-pencil"></i>
          </a>
          {% endif %}

          {% if perms.suppliers.delete_supplier %}
          <a href="{% url 'supplier_delete' supplier.id %}" class="btn btn-danger btn-sm btn-delete">
            <i class="bi bi-trash"></i>
          </a>
          {% endif %}
          
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}

suppliers/templates/supplier_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Editar Fornecedor</h3>

  <div class="card">
    <div class="card-body">
      <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar Fornecedor</button>
      </form>
    </div>
  </div>

  <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Fornecedores</a>
</div>
{% endblock %}